version: '3.4'

services:    
  hepsiyemekdb:
    container_name: hepsiyemekdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  hepsiyemek.products:
    container_name: HepsiYemekProduct
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://hepsiyemekdb:27017"
    depends_on: 
      - hepsiyemekdb
    ports:
      - "5001:80"
    #volumes:
    #  - ${HOME}/.microsoft/usersecrets/:root/.microsoft/usersecrets
